'use client';

import { useState, useEffect, useMemo, useRef } from 'react';
import dynamic from 'next/dynamic';
import { BarChart3, BookOpen, Network, Pill } from 'lucide-react';
import Image from 'next/image';
import * as Tabs from '@radix-ui/react-tabs';
import { useQueryState } from 'nuqs';
import { useDebouncedCallback } from "use-debounce";
import LeftPanel from './LeftPanel';
import OverviewTab from './OverviewTab';
import DrugTab from './DrugTab';
import PublicationTab from './PublicationTab';
import DrugClassTab from './DrugClassTab';
const AuthorNetworkTab = dynamic(() => import('./AuthorNetworkTab'), {
  ssr: false,
  loading: () => (
    <div className="flex items-center justify-center h-32">
      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
    </div>
  )
});

import {
  daGetConcepts,
  daGetDiseaseList,
  daGetDrugList,
  daGetOverallStudyType,
  daGetPMIDs,
  daGetStudy,
  daGetWordClouds,
  daGetDrugClassList,
  daGetDrugClassListByLevel,
  daExportStudy,
  daGetAuthorNetwork,
  daGetPopulationData,
} from "../dataprovider/dataaccessor";
import versionInfo from "../version.json";
import {
  ConceptRow,
  PmidRow,
  SearchType,
  StudyData
} from '../libs/database/types';
import { calculateSummaryStats, preparePlotData, preparePopulationData } from '../libs/dataprocessor/utils';
import { buildPublicationTable, PublicationTableRow } from './component-utils';



const DEFAULT_LOGO_WIDTH = 150;
const DEFAULT_LOGO_HEIGHT = 182;

const logoSize = {
  w: 100,
  h: 100 * DEFAULT_LOGO_HEIGHT / DEFAULT_LOGO_WIDTH,
};

// The landing-page population bars come from the static cache
// (`population_data`), regenerated by scripts/update_static_cache_json_file.ts.

function calculatePlotData(populationData: any[]) {
  const clinicalData = populationData.filter(item => item.ct > 0);

  const newChartLayout = {
    margin: { l: 30, r: 20, t: 10, b: 60 },
    showlegend: false,
    plot_bgcolor: 'rgba(0,0,0,0)',
    paper_bgcolor: 'rgba(0,0,0,0)',
    font: { size: 14 },
    xaxis: {
      tickangle: -45,
      tickfont: { size: 12 },
      // Population names run up to ~25 chars ("Adverse Pregnancy Outcome"); rotated
      // they need more room than a fixed bottom margin can budget for, so let Plotly
      // measure the labels and push the title clear of them.
      automargin: true,
      title: { text: 'Population', font: { size: 12 }, standoff: 12 }
    },
    yaxis: {
      tickfont: { size: 10 },
      title: { text: '', font: { size: 12 } },
      showticklabels: true
    }
  };

  const newPkChartData = [{
    x: populationData.map(d => d.name),
    y: populationData.map(d => d.pk),
    type: 'bar' as const,
    marker: {
      color: populationData.map(d => d.color),
      line: { width: 1, color: '#374151' }
    },
    text: populationData.map(d => d.pk.toString()),
    textposition: 'outside' as const,
    textfont: { size: 16 }
  }];

  const newPharmChartData = [{
    x: populationData.map(d => d.name),
    y: populationData.map(d => d.pe),
    type: 'bar' as const,
    marker: {
      color: populationData.map(d => d.color),
      line: { width: 1, color: '#374151' }
    },
    text: populationData.map(d => d.pe.toString()),
    textposition: 'outside' as const,
    textfont: { size: 16 }
  }];

  const newClinicalChartData = [{
    x: clinicalData.map(d => d.name),
    y: clinicalData.map(d => d.ct),
    type: 'bar' as const,
    marker: {
      color: clinicalData.map(d => d.color),
      line: { width: 1, color: '#374151' }
    },
    text: clinicalData.map(d => d.ct.toString()),
    textposition: 'outside' as const,
    textfont: { size: 16 }
  }];

  return {
    layout: newChartLayout,
    pkChartData: newPkChartData,
    pharmChartData: newPharmChartData,
    clinicalChartData: newClinicalChartData
  };
}

function hashPmids(pmids: PmidRow[]) {
  let hash = 5381;
  for (const item of pmids) {
    const pmid = item.pmid ?? '';
    for (let i = 0; i < pmid.length; i += 1) {
      hash = (hash * 33) ^ pmid.charCodeAt(i);
    }
  }
  return `${hash >>> 0}-${pmids.length}`;
}

function isQueryStateValid(queryState: any) {
  return queryState && queryState.length > 0;
}

export default function Home() {
  const [searchMode, setSearchMode] = useState('simple');
  const [drugList, setDrugList] = useState<string[]>([]);
  const [diseaseList, setDiseaseList] = useState<{ TERM: string, des: string }[]>([]);
  const [selectedDrug, setSelectedDrug] = useState('');
  const [selectedDisease, setSelectedDisease] = useState('');
  const [selectedDrugClass, setSelectedDrugClass] = useState('');
  const [selectedDrugClassLevel, setSelectedDrugClassLevel] = useState<1 | 2 | 3>(1);
  const [drugClassList, setDrugClassList] = useState<Array<{ value: string, label: string, preferred_label: string | null }>>([]);
  const [drugClassHierarchy, setDrugClassHierarchy] = useState<{ level1: string[], level2: string[], level3: string[] }>({
    level1: [],
    level2: [],
    level3: []
  });

  const [queryDrug, setQueryDrug] = useQueryState('drug', {
    defaultValue: '',
  });
  const [queryDisease, setQueryDisease] = useQueryState('disease', {
    defaultValue: '',
  });
  const [queryDrugClass, setQueryDrugClass] = useQueryState('drugClass', {
    defaultValue: '',
  });
  const [activeTab, setActiveTab] = useState('overview');
  const [sidebarExpanded, setSidebarExpanded] = useState(true);
  const [hasDrugSearched, setHasDrugSearched] = useState(false);
  const [isTabSwitching, setIsTabSwitching] = useState(false);
  const [pmidData, setPmidData] = useState<PmidRow[]>([]);
  const [publicationData, setPublicationData] = useState<PublicationTableRow[]>([]);
  const [publicationCount, setPublicationCount] = useState<number | null>(null);
  const [isLoadingPublications, setIsLoadingPublications] = useState(false);
  const [isLoadingPopulationData, setIsLoadingPopulationData] = useState(false);
  const [downloadType, setDownloadType] = useState<'xlsx' | 'csv' | 'tsv'>('xlsx');
  const [isExporting, setIsExporting] = useState(false);

  const pmidKey = useMemo(() => {
    if (!pmidData || pmidData.length === 0) {
      return '';
    }
    return hashPmids(pmidData);
  }, [pmidData]);

  const [overallStudyType, setOverallStudyType] = useState({
    pk: {
      count: 0,
      label: "Pharmacokinetics",
      description: "Studies examining the use and effects of drugs in large populations"
    },
    pe: {
      count: 0,
      label: "Pharmacoepidemiology",
      description: "Studies examining the use and effects of drugs in large populations"
    },
    ct: {
      count: 0,
      label: "Clinical Trial",
      description: "Controlled studies evaluating the safety and efficacy of drugs in human subjects"
    }
  });
  const [defaultPopulationData, setDefaultPopulationData] = useState<any[]>([]);
  const [populationData, setPopulationData] = useState<any[]>([]);
  const [concepts, setConcepts] = useState<ConceptRow[]>([]);

  // Chart data and layout
  const [pkChartData, setPkChartData] = useState<any[]>([]);
  const [pharmChartData, setPharmChartData] = useState<any[]>([]);
  const [clinicalChartData, setClinicalChartData] = useState<any[]>([]);
  const [chartLayout, setChartLayout] = useState<any>({
    margin: { l: 50, r: 50, t: 50, b: 50 },
    yaxis: {
      showticklabels: false,
      tickmode: 'array',
      tickvals: [],
      ticktext: []
    }
  });
  const [maternalWordCloudSvg, setMaternalWordCloudSvg] = useState("");
  const [pediatricWordCloudSvg, setPediatricWordCloudSvg] = useState("");
  const [isLoadingWordCloud, setIsLoadingWordCloud] = useState(false);
  const [authorNetworkData, setAuthorNetworkData] = useState<any | null>(null);
  const [isLoadingAuthorNetwork, setIsLoadingAuthorNetwork] = useState(false);
  const [authorNetworkError, setAuthorNetworkError] = useState<string | null>(null);
  const hasActiveQuery = Boolean(
    queryDrug?.trim() ||
    queryDisease?.trim() ||
    queryDrugClass?.trim() ||
    selectedDrug?.trim() ||
    selectedDisease?.trim() ||
    selectedDrugClass?.trim()
  );

  // initialize overview data
  // 1. populate overall study type
  // 2. populate drug list
  const initializeOverview = useDebouncedCallback(() => {
    daGetOverallStudyType().then((overall_study_type: any) => {
      setOverallStudyType(overall_study_type);
    });
    daGetDrugList().then((data: any) => {
      const drugs = (data.druglist as Array<{ name: string, type: string }>).filter(
        (item) => item.type == "drug"
      ).map(item => item.name);
      setDrugList(drugs);
    });
  });

  // Load the landing-page population bars once; the reset paths below fall back to them.
  useEffect(() => {
    const controller = new AbortController();
    daGetPopulationData({ signal: controller.signal })
      .then((data: any) => {
        setDefaultPopulationData(data?.population_data ?? []);
      })
      .catch((error: any) => {
        if (error?.name === "AbortError") return;
        console.error('Error fetching population data:', error);
      });
    return () => controller.abort();
  }, []);

  // populate disease list and set selected disease to advanced if disease is selected
  const populateDiseaseList = (disease?: string) => {
    daGetDiseaseList().then((data: any) => {
      const diseases = (data.disease as Array<{ TERM: string, des: string }>);
      setDiseaseList(diseases);
      if (disease) {
        setSelectedDisease(disease);
      }
    });
  };

  useEffect(() => {
    if (searchMode === 'advanced' && diseaseList.length === 0) {
      populateDiseaseList()
    }
  }, [searchMode]);

  // Auto-search when drug is selected in simple mode
  useEffect(() => {
    if (searchMode === 'simple' && selectedDrug) {
      // Only trigger search if drug is actually selected (not on initial render)
      // Clear disease and drug class when user selects a drug in simple mode
      setSelectedDisease('');
      setSelectedDrugClass('');
      setQueryDrug(selectedDrug);
      setQueryDisease('');
      setQueryDrugClass('');
      setConcepts([]);
      setPmidData([]);
      setPublicationData([]);
      handleTabChange("overview");
      handleConceptChange(selectedDrug, '');
    }
  }, [selectedDrug, searchMode]);

  // Load drug class hierarchy when drug class mode is selected
  useEffect(() => {
    if (searchMode === 'drugclass' && drugClassHierarchy.level1.length === 0) {
      daGetDrugClassList().then((data: any) => {
        setDrugClassHierarchy(data);
      }).catch((error: any) => {
        console.error('Error fetching drug class list:', error);
      });
    }
  }, [searchMode]);

  // Load drug class list for selected level
  useEffect(() => {
    if (searchMode === 'drugclass') {
      daGetDrugClassListByLevel(selectedDrugClassLevel).then((data: any) => {
        setDrugClassList(data);
      }).catch((error: any) => {
        console.error('Error fetching drug class list by level:', error);
      });
    }
  }, [searchMode, selectedDrugClassLevel]);

  // Auto-search when URL parameters are present on page load
  useEffect(() => {
    if (
      isQueryStateValid(queryDrug) ||
      isQueryStateValid(queryDisease) ||
      isQueryStateValid(queryDrugClass)
    ) {
      // Handle drug class query parameter
      if (isQueryStateValid(queryDrugClass)) {
        setSearchMode('drugclass');
        // Load drug class hierarchy
        daGetDrugClassList().then((data: any) => {
          setDrugClassHierarchy(data);
          // Set selected drug class and jump to DrugClass tab
          setSelectedDrugClass(queryDrugClass);
          setActiveTab('drugclass');
        }).catch((error: any) => {
          console.error('Error fetching drug class list:', error);
        });
      } else {
        // populate drug list and set selected drug to advanced if drug is selected
        daGetDrugList().then((data: any) => {
          const drugs = (data.druglist as Array<{ name: string, type: string }>).filter(
            (item) => item.type == "drug"
          ).map(item => item.name);
          setDrugList(drugs);
          if (isQueryStateValid(queryDrug)) {
            setSelectedDrug(queryDrug);
          }
        });
        if (isQueryStateValid(queryDisease)) {
          setSearchMode('advanced');
          populateDiseaseList(queryDisease);
        }
        // Trigger search after a short delay to ensure data is loaded
        const timer = setTimeout(() => {
          if (isQueryStateValid(queryDrug) || isQueryStateValid(queryDisease)) {
            handleConceptChange(queryDrug ?? "", queryDisease ?? "");
          }
        }, 100);
        return () => clearTimeout(timer);
      }
    } else {
      initializeOverview();
    }
  }, []);

  useEffect(() => {
    const controller = new AbortController();
    const { signal } = controller;
    let isActive = true;

    if (!pmidData || pmidData.length === 0 || !pmidKey) {
      setPublicationData([]);
      setPublicationCount(0);
      setIsLoadingPublications(false);
      setIsLoadingPopulationData(false);
      if (hasActiveQuery) {
        setOverallStudyType(prev => ({
          ...prev,
          pk: { ...prev.pk, count: 0 },
          pe: { ...prev.pe, count: 0 },
          ct: { ...prev.ct, count: 0 },
        }));
        setPopulationData([]);
      } else {
        setPopulationData(defaultPopulationData);
      }
      return () => {
        isActive = false;
        controller.abort();
      };
    }

    const applyDerivedData = (studyData: StudyData[]) => {
      const derivedTypeData = studyData.map(item => ({
        pmid: item.PMID,
        study_type: item.StudyType || "",
        population: item.Population || "",
        maternal_score_pk: item.maternal_score_pk ?? null,
        maternal_score_pe: item.maternal_score_pe ?? null,
        maternal_score_ct: item.maternal_score_ct ?? null,
        pediatric_score_pk: item.pediatric_score_pk ?? null,
        pediatric_score_pe: item.pediatric_score_pe ?? null,
        pediatric_score_ct: item.pediatric_score_ct ?? null,
      }));

      const summaryStats = calculateSummaryStats(derivedTypeData);
      setOverallStudyType(prev => ({
        ...prev,
        pk: { ...prev.pk, count: summaryStats.find(stat => stat.study_type.toLowerCase() === "pk")?.count ?? 0 },
        pe: { ...prev.pe, count: summaryStats.find(stat => stat.study_type.toLowerCase() === "pe")?.count ?? 0 },
        ct: { ...prev.ct, count: summaryStats.find(stat => stat.study_type.toLowerCase() === "ct")?.count ?? 0 },
      }));

      const pkPlotData = preparePlotData("PK", derivedTypeData);
      const pePlotData = preparePlotData("PE", derivedTypeData);
      const ctPlotData = preparePlotData("CT", derivedTypeData);
      const thePopulationData = preparePopulationData(pkPlotData, pePlotData, ctPlotData);
      setPopulationData(thePopulationData);
    };

    setIsLoadingPublications(true);
    setPublicationData([]);

    daGetStudy(pmidData, { signal })
      .then((data: any) => {
        if (!isActive) return;
        const studyData = data as StudyData[];

        applyDerivedData(studyData);
        setPublicationData(buildPublicationTable(studyData));
        setPublicationCount(studyData.length);
        setIsLoadingPublications(false);
        setIsLoadingPopulationData(false);
      })
      .catch((error: any) => {
        if (!isActive || error?.name === "AbortError") return;
        console.error("Error fetching study data:", error);
        setIsLoadingPublications(false);
        setIsLoadingPopulationData(false);
      });

    return () => {
      isActive = false;
      controller.abort();
    };
  }, [pmidData, pmidKey, hasActiveQuery, defaultPopulationData]);

  // Handle window resize for responsive charts
  useEffect(() => {
    const handleResize = () => {
      // Trigger Plotly resize event
      if (typeof window !== 'undefined' && (window as any).Plotly) {
        const plotElements = document.querySelectorAll('.js-plotly-plot');
        plotElements.forEach((element) => {
          (window as any).Plotly.Plots.resize(element);
        });
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Generate chart data when population data changes
  useEffect(() => {
    const { layout, pkChartData, pharmChartData, clinicalChartData } = calculatePlotData(populationData);

    setChartLayout(layout);
    setPkChartData(pkChartData);
    setPharmChartData(pharmChartData);
    setClinicalChartData(clinicalChartData);
  }, [populationData]);


  useEffect(() => {
    const controller = new AbortController();
    const { signal } = controller;
    let isActive = true;

    if (!pmidData || pmidData.length === 0 || !pmidKey) {
      setMaternalWordCloudSvg("");
      setPediatricWordCloudSvg("");
      setIsLoadingWordCloud(false);
      return () => {
        isActive = false;
        controller.abort();
      };
    }

    setIsLoadingWordCloud(true);
    const searchWords = [selectedDrug, selectedDisease].filter(Boolean);
    daGetWordClouds(pmidData, searchWords, { signal })
      .then((data: any) => {
        if (!isActive) return;
        setMaternalWordCloudSvg(data?.maternal ?? "");
        setPediatricWordCloudSvg(data?.pediatric ?? "");
        setIsLoadingWordCloud(false);
      })
      .catch((error: any) => {
        if (!isActive || error?.name === "AbortError") return;
        console.error("Error fetching mesh terms:", error);
        setIsLoadingWordCloud(false);
      });

    return () => {
      isActive = false;
      controller.abort();
    };
  }, [pmidData, pmidKey, selectedDrug, selectedDisease]);

  useEffect(() => {
    const controller = new AbortController();
    const { signal } = controller;
    let isActive = true;

    if (activeTab !== 'author-network') {
      return () => {
        isActive = false;
        controller.abort();
      };
    }

    if (!pmidData || pmidData.length === 0 || !pmidKey) {
      setAuthorNetworkData(null);
      setAuthorNetworkError(null);
      setIsLoadingAuthorNetwork(false);
      return () => {
        isActive = false;
        controller.abort();
      };
    }

    setIsLoadingAuthorNetwork(true);
    setAuthorNetworkError(null);
    daGetAuthorNetwork(pmidData, { minEdgeWeight: 1 }, { signal })
      .then((data: any) => {
        if (!isActive) return;
        setAuthorNetworkData(data ?? null);
        setIsLoadingAuthorNetwork(false);
      })
      .catch((error: any) => {
        if (!isActive || error?.name === "AbortError") return;
        console.error("Error fetching author network:", error);
        setAuthorNetworkError("Failed to load author network");
        setIsLoadingAuthorNetwork(false);
      });

    return () => {
      isActive = false;
      controller.abort();
    };
  }, [pmidData, pmidKey, activeTab]);

  function handleTabChange(value: string) {
    setIsTabSwitching(true);
    setActiveTab(value);
    // Small delay to show loading state
    setTimeout(() => setIsTabSwitching(false), 150);
  }

  const handleConceptChange = useDebouncedCallback((drug: string, disease: string) => {
    // Don't search if both parameters are empty
    if (!drug && !disease) {
      return;
    }

    // Set loading state for population data
    setIsLoadingPopulationData(true);

    // Ensure we have valid string parameters
    const safeDrug = String(drug || '');
    const safeDisease = String(disease || '');

    daGetConcepts(safeDrug, safeDisease).then((data: any) => {
      const concepts: ConceptRow[] = Array.isArray(data) ? (data as ConceptRow[]) : [];
      if (concepts.length === 0) {
        setConcepts([]);
        setPmidData([]);
        setHasDrugSearched(false);
        setOverallStudyType(prev => ({
          ...prev,
          pk: { ...prev.pk, count: 0 },
          pe: { ...prev.pe, count: 0 },
          ct: { ...prev.ct, count: 0 },
        }));
        setPopulationData([]);
        setIsLoadingPopulationData(false);
        return;
      }
      const isDrugConceptQueried = concepts.some(concept => concept.type === "drug");
      setHasDrugSearched(isDrugConceptQueried);
      setConcepts(concepts);
      const searchType: SearchType = [];
      if (safeDrug) {
        searchType.push("Drug");
      }
      if (safeDisease) {
        searchType.push("Disease");
      }
      daGetPMIDs(data, searchType).then((pmidData: any) => {
        setPmidData(pmidData);
      }).catch((error: any) => {
        console.error('Error fetching PMIDs:', error);
        setIsLoadingPopulationData(false);
      });
    }).catch((error: any) => {
      console.error('Error fetching concepts:', error);
      setIsLoadingPopulationData(false);
    });
  }, 500);

  function handleSearch() {
    if (!selectedDrug && !selectedDisease) {
      return; // Don't search if no parameters are selected
    }
    // Clear drug class when searching in Advanced mode (since Advanced mode uses drug/disease)
    setConcepts([]);
    setPmidData([]);
    setSelectedDrugClass('');
    setQueryDrugClass('');
    setQueryDrug(selectedDrug ?? "");
    setQueryDisease(selectedDisease ?? "");
    setPublicationData([]);
    handleTabChange("overview");
    handleConceptChange(selectedDrug, selectedDisease);
  }

  function handleSearchModeChange(e: any) {
    setSearchMode(e.target.value);
    // Reset drug class level to 1 when switching to drug class mode
    if (e.target.value === 'drugclass') {
      setSelectedDrugClassLevel(1);
    }
    // Don't clear selections when switching modes - only clear when user makes new selections
  }

  function clearAllSearch() {
    try {
      setSelectedDrug('');
      setSelectedDisease('');
      setSelectedDrugClass('');
      setSelectedDrugClassLevel(1);
      setQueryDrug('');
      setQueryDisease('');
      setQueryDrugClass('');
      setIsLoadingPopulationData(false);
      initializeOverview();
      setPopulationData(defaultPopulationData);
    } catch (error) {
      console.warn('Error clearing search parameters:', error);
    }
    setConcepts([]);
    setPmidData([]);
    setPublicationData([]);
    setHasDrugSearched(false);
    setActiveTab('overview');
  }

  function handleDrugChange(drug: string) {
    if (searchMode === 'simple') {
      setPmidData([]);
      setPublicationData([]);
    }
    setSelectedDrug(drug);
    if (searchMode === 'simple') {
      setQueryDrug(drug);
      if (drug) {
        setSelectedDrugClass('');
        setQueryDrugClass('');
        setSelectedDisease('');
        setQueryDisease('');
      }
    }
  }

  function handleDrugClassChange(drugClass: string) {
    setSelectedDrugClass(drugClass);
    if (drugClass) {
      // Set query parameter
      setQueryDrugClass(drugClass);
      // Clear drug and disease selections
      setSelectedDrug('');
      setSelectedDisease('');
      setQueryDrug('');
      setQueryDisease('');
      // Set search mode to drugclass
      setSearchMode('drugclass');
      // Jump to DrugClass tab
      setActiveTab('drugclass');
      setHasDrugSearched(false);
      setConcepts([]);
    } else {
      // Clear query parameter when drug class is cleared
      setQueryDrugClass('');
      // Reset to overview tab when clearing
      setActiveTab('overview');
    }
  }

  function handleDrugClassLevelChange(level: 1 | 2 | 3) {
    setSelectedDrugClassLevel(level);
    // Clear selected drug class when level changes
    setSelectedDrugClass('');
    setQueryDrugClass('');
    setActiveTab('overview');
  }

  async function handleDownload() {
    if (!pmidData || pmidData.length === 0 || isExporting) {
      return;
    }
    setIsExporting(true);
    try {
      const { blob, filename } = await daExportStudy(pmidData, downloadType);
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    } catch (error) {
      console.error('Error exporting publication data:', error);
    } finally {
      setIsExporting(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="mprint-header-bg-blue shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <a style={{ marginLeft: `${logoSize.w - 8}px` }} href="https://www.mprint.org/" target="_blank">
                  <Image src="/images/mprint-logo.png" alt="mprint logo" width="180" height="60" priority />
                </a>
              </div>
              <h1 className="text-xl font-semibold text-gray-900">Knowledge Portal (Silver)</h1>
              <span className="text-xs font-mono text-gray-500 self-center">
                v{versionInfo.version}
              </span>
            </div>
            <nav className="flex space-x-8">
              <a href="/" className="text-gray-500 hover:text-gray-700 px-1 py-2 text-sm font-medium">
                Explore
              </a>
              <a href="/about" className="text-gray-500 hover:text-gray-700 px-1 py-2 text-sm font-medium">
                About
              </a>
            </nav>
          </div>
        </div>
      </header>

      <div className="flex">
        {/* Left Sidebar */}
        <LeftPanel
          searchMode={searchMode}
          onSearchModeChange={handleSearchModeChange}
          drugList={drugList}
          diseaseList={diseaseList}
          selectedDrug={selectedDrug}
          selectedDisease={selectedDisease}
          selectedDrugClass={selectedDrugClass}
          selectedDrugClassLevel={selectedDrugClassLevel}
          drugClassList={drugClassList}
          drugClassHierarchy={drugClassHierarchy}
          onDrugChange={handleDrugChange}
          onDiseaseChange={setSelectedDisease}
          onDrugClassChange={handleDrugClassChange}
          onDrugClassLevelChange={handleDrugClassLevelChange}
          onSearch={handleSearch}
          onClearAll={clearAllSearch}
          downloadType={downloadType}
          onDownloadTypeChange={setDownloadType}
          onDownload={handleDownload}
          isExporting={isExporting}
          pmidData={pmidData}
          sidebarExpanded={sidebarExpanded}
          onSidebarToggle={() => setSidebarExpanded(!sidebarExpanded)}
        />

        {/* Main Content */}
        <div className="flex-1 min-w-0 bg-white p-10">
          {/* Tabs */}
          <Tabs.Root
            value={activeTab}
            onValueChange={handleTabChange}
            className="w-full"
            defaultValue="overview"
          >
            <Tabs.List
              className="flex border-b border-gray-200 mb-8"
              aria-label="Dashboard navigation tabs"
            >
              <Tabs.Trigger
                value="overview"
                className="flex items-center space-x-2 px-3 py-2 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 data-[state=active]:border-blue-500 data-[state=active]:text-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                <BarChart3 className="w-4 h-4" />
                <span>Overview</span>
              </Tabs.Trigger>

              {selectedDrugClass && (
                <Tabs.Trigger
                  value="drugclass"
                  className="flex items-center space-x-2 px-3 py-2 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 data-[state=active]:border-blue-500 data-[state=active]:text-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <BarChart3 className="w-4 h-4" />
                  <span>Drug & Publication</span>
                </Tabs.Trigger>
              )}

              {hasDrugSearched && (
                <Tabs.Trigger
                  value="drug"
                  className="flex items-center space-x-2 px-3 py-2 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 data-[state=active]:border-blue-500 data-[state=active]:text-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <Pill className="w-4 h-4" />
                  <span>Drug</span>
                </Tabs.Trigger>
              )}

              {concepts.length > 0 && (
                <Tabs.Trigger
                  value="publication"
                  className="flex items-center space-x-2 px-3 py-2 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 data-[state=active]:border-blue-500 data-[state=active]:text-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <BookOpen className="w-4 h-4" />
                  <span>Publication</span>
                </Tabs.Trigger>
              )}

              {pmidData.length > 0 && (
                <Tabs.Trigger
                  value="author-network"
                  className="flex items-center space-x-2 px-3 py-2 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 data-[state=active]:border-blue-500 data-[state=active]:text-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <Network className="w-4 h-4" />
                  <span>Author Network</span>
                </Tabs.Trigger>
              )}

            </Tabs.List>

            <Tabs.Content
              value="overview"
              className="outline-none animate-in fade-in-0 slide-in-from-left-1 duration-300"
            >
              {isTabSwitching && activeTab !== 'overview' ? (
                <div className="flex items-center justify-center h-32">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                </div>
              ) : (
                <OverviewTab
                  overallStudyType={overallStudyType}
                  pkChartData={pkChartData}
                  pharmChartData={pharmChartData}
                  clinicalChartData={clinicalChartData}
                  chartLayout={chartLayout}
                  isLoadingPopulationData={isLoadingPopulationData}
                  maternalWordCloudSvg={maternalWordCloudSvg}
                  pediatricWordCloudSvg={pediatricWordCloudSvg}
                  isLoadingWordCloud={isLoadingWordCloud}
                />
              )}
            </Tabs.Content>

            {selectedDrugClass && (
              <Tabs.Content
                value="drugclass"
                className="outline-none animate-in fade-in-0 slide-in-from-left-1 duration-300"
              >
                {isTabSwitching && activeTab !== 'drugclass' ? (
                  <div className="flex items-center justify-center h-32">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                  </div>
                ) : (
                  <DrugClassTab selectedDrugClass={selectedDrugClass} />
                )}
              </Tabs.Content>
            )}

            {hasDrugSearched && (
              <Tabs.Content
                value="drug"
                className="outline-none animate-in fade-in-0 slide-in-from-right-1 duration-300"
              >
                {isTabSwitching && activeTab !== 'drug' ? (
                  <div className="flex items-center justify-center h-32">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                  </div>
                ) : (
                  <DrugTab selectedDrug={selectedDrug} concepts={concepts} />
                )}
              </Tabs.Content>
            )}

            {concepts.length > 0 && (
              <Tabs.Content
                value="publication"
                className="outline-none animate-in fade-in-0 slide-in-from-right-1 duration-300"
              >
                {isTabSwitching && activeTab !== 'publication' ? (
                  <div className="flex items-center justify-center h-32">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                  </div>
                ) : (
                  <PublicationTab
                    publicationData={publicationData}
                    publicationCount={publicationCount}
                    estimatedCount={pmidData.length}
                    isLoading={isLoadingPublications}
                  />
                )}
              </Tabs.Content>
            )}

            {pmidData.length > 0 && (
              <Tabs.Content
                value="author-network"
                className="outline-none animate-in fade-in-0 slide-in-from-right-1 duration-300"
              >
                {isTabSwitching && activeTab !== 'author-network' ? (
                  <div className="flex items-center justify-center h-32">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                  </div>
                ) : (
                  <AuthorNetworkTab
                    data={authorNetworkData}
                    isLoading={isLoadingAuthorNetwork}
                    error={authorNetworkError}
                  />
                )}
              </Tabs.Content>
            )}

          </Tabs.Root>
        </div>
      </div>
    </div>
  );
}
